### ISSUE TITLE
Stack size and connecting/leaving a table shoud be shared between players

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/bet#42]
Currently, there is no way to know at the player nodes that:

- When another player joins or leaves the table
- How much is the other player's stack when they join

We should have a mechanism for sharing this info.

**Comment by sg777** [comment]
This has been implemented, in the current code base whenever the player joins the respective information is shared across the players. For the info about the player disconnection a heartbeat protocol is implemented in the backend, it needs to be integrated with the GUI with little enhancements which I'm been working on it.

**Comment by sg777** [comment]
Implemented updating the status info of the players to each others during the disconnections in https://github.com/chips-blockchain/bet/commit/0159fa8e74d354a641c92a472a4f6d173f59f6bf. 
So now periodically for every 5 seconds, the players info is pushed to the GUI. The example json info which it was used to push to the GUI is as below and which means that players with playerid's 0 and 1(since we start the playerid's from 0) are active.
```
{
method: "active_player_info", 
player_status: [1, 1]
}
```
